variables:
  IMAGE_NAME: ${REGISTRY_SERVER}/ruining/vscode-remote
stages:
  - build
  - publish
container:
  only:
    variables:
      - $CI_COMMIT_MESSAGE =~ /^\[Build Image\].*/
  stage: publish
  image: quay.xiaodiankeji.net/buildah/stable:latest
  before_script:
    - buildah version
    - buildah login --username "${REGISTRY_USERNAME}" --password "${REGISTRY_PASSWORD}" "${REGISTRY_SERVER}"
  script:
    - buildah bud --build-arg HTTP_PROXY=${HTTP_PROXY} --build-arg HTTPS_PROXY=${HTTPS_PROXY} -t ${IMAGE_NAME}:${CI_COMMIT_SHORT_SHA} .
    - buildah push ${IMAGE_NAME}:${CI_COMMIT_SHORT_SHA} docker://${IMAGE_NAME}:${CI_COMMIT_SHORT_SHA}
  after_script:
    - buildah logout "${REGISTRY_SERVER}"
