name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    if: "!contains(github.event.head_commit.message, '[SKIP CI]')"
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag quay.io/${{ github.actor }}/code-server:$GITHUB_RUN_ID
    - name: Log into registry
      run: echo "${{ secrets.PASSWORD }}" | docker login quay.io -u ${{ github.actor }} --password-stdin 
    - name: Push image
      run: docker push quay.io/${{ github.actor }}/code-server:$GITHUB_RUN_ID
